services:
    mongodb:
        image:  mongo
        restart: always 
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: root
        volumes:
            - mongo-vol:/data/db
 
    mongo-express: 
        image: mongo-express
        restart: always 
        ports: 
            - 8081:8081
        environment:
                ME_CONFIG_MONGODB_ADMINUSERNAME: admin
                ME_CONFIG_MONGODB_ADMINPASSWORD: root
                ME_CONFIG_MONGODB_URL: mongodb://admin:root@mongodb:27017/     

    recomm-api:
        image: recomm-api
        ports:
            - 5000:5000
        environment:
            ENV_MongoConnectionString: mongodb://admin:root@mongodb:27017/

    recomm-ui:
        image: recomm-ui
        ports:
            - 3000:3000
volumes:
    mongo-vol:
